package com.graduation.crm.modules.note.service;

import com.graduation.crm.modules.note.dto.NoteAutoGenerateDTO;
import com.graduation.crm.modules.note.dto.NoteCreateDTO;
import com.graduation.crm.modules.note.dto.NoteUpdateDTO;
import com.graduation.crm.modules.note.vo.NoteVO;

import java.util.List;

public interface NoteService {

    NoteVO autoGenerate(NoteAutoGenerateDTO dto);

    Long create(NoteCreateDTO dto);

    void update(Long id, NoteUpdateDTO dto);

    void delete(Long id);

    NoteVO detail(Long id);

    List<NoteVO> listByCustomerId(Long customerId);
}

