package com.graduation.crm.modules.note.service.impl;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.graduation.crm.common.exception.BusinessException;
import com.graduation.crm.modules.ai.client.QwenAiClient;
import com.graduation.crm.modules.ai.dto.AiChatDTO;
import com.graduation.crm.modules.ai.vo.AiChatVO;
import com.graduation.crm.modules.customer.service.CustomerService;
import com.graduation.crm.modules.customer.vo.CustomerDetailVO;
import com.graduation.crm.modules.follow.entity.FollowRecord;
import com.graduation.crm.modules.follow.mapper.FollowRecordMapper;
import com.graduation.crm.modules.note.dto.NoteAutoGenerateDTO;
import com.graduation.crm.modules.note.dto.NoteCreateDTO;
import com.graduation.crm.modules.note.dto.NoteUpdateDTO;
import com.graduation.crm.modules.note.entity.Note;
import com.graduation.crm.modules.note.mapper.NoteMapper;
import com.graduation.crm.modules.note.service.NoteService;
import com.graduation.crm.modules.note.vo.NoteVO;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class NoteServiceImpl implements NoteService {

    private final NoteMapper noteMapper;
    private final FollowRecordMapper followRecordMapper;
    private final CustomerService customerService;
    private final QwenAiClient qwenAiClient;
    private final ObjectMapper objectMapper;

    @Override
    public NoteVO autoGenerate(NoteAutoGenerateDTO dto) {
        CustomerDetailVO customer = customerService.detail(dto.getCustomerId());
        FollowRecord follow = followRecordMapper.selectById(dto.getFollowId());
        if (follow == null || !dto.getCustomerId().equals(follow.getCustomerId())) {
            throw new BusinessException("跟进记录不存在或不属于该客户");
        }

        AiChatDTO chatDTO = new AiChatDTO();
        chatDTO.setBizType("NOTE");
        chatDTO.setBizId(dto.getFollowId());
        chatDTO.setPrompt(buildNotePrompt(customer, follow));
        AiChatVO chatVO = qwenAiClient.chat(chatDTO);

        NoteCreateDTO createDTO = parseGeneratedNote(chatVO.getContent());
        createDTO.setCustomerId(dto.getCustomerId());
        createDTO.setFollowId(dto.getFollowId());
        createDTO.setNoteType("AUTO");
        createDTO.setCreatedBy(dto.getCreatedBy());
        Long noteId = create(createDTO);
        return detail(noteId);
    }

    @Override
    public Long create(NoteCreateDTO dto) {
        Note note = new Note();
        BeanUtils.copyProperties(dto, note);
        note.setNoteType(dto.getNoteType() == null ? "MANUAL" : dto.getNoteType());
        noteMapper.insert(note);
        return note.getId();
    }

    @Override
    public void update(Long id, NoteUpdateDTO dto) {
        Note note = noteMapper.selectById(id);
        if (note == null) {
            throw new BusinessException("笔记不存在");
        }
        BeanUtils.copyProperties(dto, note);
        noteMapper.updateById(note);
    }

    @Override
    public void delete(Long id) {
        Note note = noteMapper.selectById(id);
        if (note == null) {
            throw new BusinessException("笔记不存在");
        }
        // 当前表没有 deleted 字段，删除笔记采用物理删除；如需审计可后续补 deleted 字段。
        noteMapper.deleteById(id);
    }

    @Override
    public NoteVO detail(Long id) {
        NoteVO note = noteMapper.selectNoteDetail(id);
        if (note == null) {
            throw new BusinessException("笔记不存在");
        }
        return note;
    }

    @Override
    public List<NoteVO> listByCustomerId(Long customerId) {
        return noteMapper.selectByCustomerId(customerId);
    }

    private String buildNotePrompt(CustomerDetailVO customer, FollowRecord follow) {
        StringBuilder prompt = new StringBuilder();
        prompt.append("你是房地产销售跟进复盘助手。请根据客户资料和本次跟进内容生成云笔记。");
        prompt.append("只返回 JSON，不要 Markdown，不要解释。字段固定为：title,summary,objectionTop3,nextTopic。");
        prompt.append("summary 控制在120字以内，objectionTop3 用中文分号分隔最多3项，nextTopic 给出下一次沟通主题。");
        prompt.append("\n客户姓名：").append(customer.getCustomerName());
        prompt.append("\n客户状态：").append(customer.getStatus());
        prompt.append("\n意向等级：").append(customer.getIntentLevel());
        prompt.append("\n预算：").append(customer.getBudgetMin()).append("-").append(customer.getBudgetMax());
        prompt.append("\n区域/户型：").append(customer.getRegion()).append("/").append(customer.getHouseType());
        prompt.append("\n客户标签：").append(customer.getTagNames());
        prompt.append("\n跟进方式：").append(follow.getFollowType());
        prompt.append("\n跟进结果：").append(follow.getFollowResult());
        prompt.append("\n跟进内容：").append(follow.getContent());
        prompt.append("\n已有摘要：").append(follow.getSummary());
        return prompt.toString();
    }

    private NoteCreateDTO parseGeneratedNote(String content) {
        try {
            String json = normalizeJson(content);
            JsonNode root = objectMapper.readTree(json);
            NoteCreateDTO dto = new NoteCreateDTO();
            dto.setTitle(textOrDefault(root, "title", "AI跟进复盘"));
            dto.setSummary(textOrDefault(root, "summary", content));
            dto.setObjectionTop3(textOrDefault(root, "objectionTop3", ""));
            dto.setNextTopic(textOrDefault(root, "nextTopic", ""));
            return dto;
        } catch (Exception e) {
            throw new BusinessException("AI复盘结果解析失败，请重试或手动新增笔记");
        }
    }

    private String normalizeJson(String content) {
        String text = content == null ? "" : content.trim();
        if (text.startsWith("```")) {
            text = text.replaceFirst("^```json", "").replaceFirst("^```", "");
            if (text.endsWith("```")) {
                text = text.substring(0, text.length() - 3);
            }
        }
        int start = text.indexOf('{');
        int end = text.lastIndexOf('}');
        if (start >= 0 && end > start) {
            return text.substring(start, end + 1);
        }
        return text;
    }

    private String textOrDefault(JsonNode root, String field, String defaultValue) {
        JsonNode node = root.get(field);
        if (node == null || node.isNull()) {
            return defaultValue;
        }
        return node.asText();
    }
}

