package com.graduation.crm.modules.note.dto;

import lombok.Data;

import javax.validation.constraints.NotNull;

@Data
public class NoteAutoGenerateDTO {

    @NotNull(message = "客户ID不能为空")
    private Long customerId;

    @NotNull(message = "跟进记录ID不能为空")
    private Long followId;

    @NotNull(message = "创建人不能为空")
    private Long createdBy;
}

