package com.graduation.crm.modules.note.controller;

import com.graduation.crm.common.result.Result;
import com.graduation.crm.modules.note.dto.NoteAutoGenerateDTO;
import com.graduation.crm.modules.note.dto.NoteCreateDTO;
import com.graduation.crm.modules.note.dto.NoteUpdateDTO;
import com.graduation.crm.modules.note.service.NoteService;
import com.graduation.crm.modules.note.vo.NoteVO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;

/**
 * 小程序端云笔记接口。
 *
 * 支持跟进后 AI 自动复盘，也支持顾问手动维护客户笔记。
 */
@Tag(name = "移动端云笔记接口")
@RestController
@RequestMapping("/api/app")
@RequiredArgsConstructor
public class AppNoteController {

    private final NoteService noteService;

    /**
     * 根据指定跟进记录生成 AI 复盘云笔记。
     */
    @PostMapping("/notes/auto-generate")
    @Operation(summary = "AI生成复盘笔记")
    public Result<NoteVO> autoGenerate(@RequestBody @Valid NoteAutoGenerateDTO dto) {
        return Result.success(noteService.autoGenerate(dto));
    }

    /**
     * 手动新增客户云笔记。
     */
    @PostMapping("/notes")
    @Operation(summary = "新增云笔记")
    public Result<Long> create(@RequestBody @Valid NoteCreateDTO dto) {
        return Result.success(noteService.create(dto));
    }

    /**
     * 查询客户笔记列表，用于客户详情页复盘区。
     */
    @GetMapping("/customers/{customerId}/notes")
    @Operation(summary = "查询客户云笔记")
    public Result<List<NoteVO>> listByCustomerId(@PathVariable Long customerId) {
        return Result.success(noteService.listByCustomerId(customerId));
    }

    /**
     * 查询云笔记详情。
     */
    @GetMapping("/notes/{id}")
    @Operation(summary = "查询云笔记详情")
    public Result<NoteVO> detail(@PathVariable Long id) {
        return Result.success(noteService.detail(id));
    }

    /**
     * 编辑云笔记内容。
     */
    @PutMapping("/notes/{id}")
    @Operation(summary = "更新云笔记")
    public Result<Void> update(@PathVariable Long id, @RequestBody NoteUpdateDTO dto) {
        noteService.update(id, dto);
        return Result.success();
    }

    /**
     * 删除云笔记。
     */
    @DeleteMapping("/notes/{id}")
    @Operation(summary = "删除云笔记")
    public Result<Void> delete(@PathVariable Long id) {
        noteService.delete(id);
        return Result.success();
    }
}

